// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rsndsydjbcqlmkjkrosj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzbmRzeWRqYmNxbG1ramtyb3NqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMTM2MjMsImV4cCI6MjA2OTU4OTYyM30.ADnsve-MfMIKV_6cpVBXaD2Do55Tzv2usbQUWkZdTMw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});